name: image_recognition_scanner_example
description: Demonstrates how to use the image_recognition_scanner plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: 1.0.5
  flutter:
    sdk: flutter
  image_recognition_scanner:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_quido: 0.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/reference_images/
