name: ar_quido
description: A new Flutter project.
version: 0.0.1
homepage: https://miquido.com

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.3
  stream_transform: 2.1.0

dev_dependencies:
  async: 2.10.0
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  lint_quido: 0.4.0
  mockito: 5.3.2


flutter:
  plugin:
    platforms:
      android:
        package: com.miquido.ar_quido
        pluginClass: ARQuidoPlugin
      ios:
        pluginClass: ARQuidoPlugin
